### ISSUE TITLE
Memory Leaks with LabelProgress

### ISSUE THREAD

**Issue by ryanfrancesconi** [orchetect/OTOperations#12]
Putting this here till I have time to look or if you want to.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/2917795/156428201-603e0203-7b73-4692-803e-f6caf0ebf008.png">

**Comment by orchetect** [comment]
Ah nice catch - yes, cancellationHandler closure was capturing a strong reference when it should have been weak. I'll push a release momentarily with a fix.
